#############################################################################
# Makefile for building: examen.app/Contents/MacOS/examen
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  examen.pro
# Template: app
# Command: /Users/xavi/Qt/5.5/clang_64/bin/qmake -o Makefile examen.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/glew/1.12.0/include -I/usr/local/Cellar/glm/0.9.7.1/include -I../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/xavi/Qt/5.5/clang_64/lib
QMAKE         = /Users/xavi/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = examen1.0.0
DISTDIR = /Users/xavi/IDI/IDIcasa/Examen-Grup10/examen/.tmp/examen1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/xavi/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/xavi/Qt/5.5/clang_64/lib /usr/local/Cellar/glew/1.12.0/lib/libGLEW.1.12.0.dylib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MyGLWidget.cpp \
		Model/model.cpp moc_MyGLWidget.cpp
OBJECTS       = main.o \
		MyGLWidget.o \
		model.o \
		moc_MyGLWidget.o
DIST          = ../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		examen.pro MyGLWidget.h main.cpp \
		MyGLWidget.cpp \
		Model/model.cpp
QMAKE_TARGET  = examen
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = examen.app/Contents/MacOS/examen

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d examen.app/Contents/MacOS/ || mkdir -p examen.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: examen.pro ../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		examen.pro \
		/Users/xavi/Qt/5.5/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/xavi/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/xavi/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/xavi/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile examen.pro
../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
examen.pro:
/Users/xavi/Qt/5.5/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/xavi/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/xavi/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/xavi/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile examen.pro

qmake_all: FORCE

examen.app/Contents/PkgInfo: 
	@test -d examen.app/Contents || mkdir -p examen.app/Contents
	@$(DEL_FILE) examen.app/Contents/PkgInfo
	@echo "APPL????" > examen.app/Contents/PkgInfo
examen.app/Contents/Resources/empty.lproj: 
	@test -d examen.app/Contents/Resources || mkdir -p examen.app/Contents/Resources
	@touch examen.app/Contents/Resources/empty.lproj
	
examen.app/Contents/Info.plist: 
	@test -d examen.app/Contents || mkdir -p examen.app/Contents
	@$(DEL_FILE) examen.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.examen,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,examen,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >examen.app/Contents/Info.plist

all: Makefile \
		examen.app/Contents/PkgInfo \
		examen.app/Contents/Resources/empty.lproj \
		examen.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents MyGLWidget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MyGLWidget.cpp Model/model.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r examen.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_MyGLWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MyGLWidget.cpp
moc_MyGLWidget.cpp: ../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLShader \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLShaderProgram \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/glm.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_fixes.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/fwd.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_int.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/setup.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_float.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/precision.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_swizzle.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_swizzle_func.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_sse2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_avx.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_avx2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/trigonometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_trigonometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_trigonometric.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_vectorize.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec1.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec1.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/exponential.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_exponential.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_exponential.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_vector_relational.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_vector_relational.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/common.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_common.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_common.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/packing.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_packing.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_packing.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_half.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_half.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/geometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_geometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_geometric.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/matrix.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_matrix.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_matrix.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vector_relational.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/integer.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_integer.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_integer.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/matrix_transform.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/constants.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/constants.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/matrix_transform.inl \
		MyGLWidget.h
	/Users/xavi/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/xavi/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/xavi/IDI/IDIcasa/Examen-Grup10/examen -I/usr/local/Cellar/glew/1.12.0/include -I/usr/local/Cellar/glm/0.9.7.1/include -I/Users/xavi/Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers -I/Users/xavi/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/xavi/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/xavi/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/xavi/Qt/5.5/clang_64/lib MyGLWidget.h -o moc_MyGLWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		MyGLWidget.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLShader \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLShaderProgram \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/glm.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_fixes.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/fwd.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_int.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/setup.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_float.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/precision.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_swizzle.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_swizzle_func.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_sse2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_avx.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_avx2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/trigonometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_trigonometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_trigonometric.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_vectorize.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec1.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec1.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/exponential.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_exponential.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_exponential.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_vector_relational.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_vector_relational.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/common.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_common.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_common.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/packing.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_packing.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_packing.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_half.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_half.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/geometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_geometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_geometric.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/matrix.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_matrix.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_matrix.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vector_relational.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/integer.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_integer.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_integer.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/matrix_transform.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/constants.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/constants.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/matrix_transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MyGLWidget.o: MyGLWidget.cpp /usr/local/Cellar/glew/1.12.0/include/GL/glew.h \
		MyGLWidget.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLShader \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		../../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers/QGLShaderProgram \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/glm.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_fixes.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/fwd.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_int.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/setup.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_float.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/precision.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_swizzle.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_swizzle_func.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vec4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_sse2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_avx.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec4_avx2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat2x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat2x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat3x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat3x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x2.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x2.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x3.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x3.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/mat4x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x4.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_mat4x4.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/trigonometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_trigonometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_trigonometric.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/_vectorize.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec1.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_vec1.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/exponential.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_exponential.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_exponential.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_vector_relational.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_vector_relational.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/common.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_common.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_common.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/packing.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_packing.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_packing.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_half.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/type_half.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/geometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_geometric.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_geometric.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/matrix.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_matrix.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_matrix.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/vector_relational.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/integer.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_integer.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/detail/func_integer.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/matrix_transform.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/constants.hpp \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/constants.inl \
		/usr/local/Cellar/glm/0.9.7.1/include/glm/gtc/matrix_transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyGLWidget.o MyGLWidget.cpp

model.o: Model/model.cpp Model/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o Model/model.cpp

moc_MyGLWidget.o: moc_MyGLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyGLWidget.o moc_MyGLWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

